// Maps every chapter heading in source/Fractalism_Complete.md to a site node.
// `heading` must exactly match the text after "## " in the source.
// `related` is the curated "where next" graph — first entry is the featured next step.
// Summaries double as the hook text shown when another page links here.

export const PARTS = {
  'front': { title: 'Front Matter', color: 'var(--c-neutral)' },
  'part-one': {
    title: 'Part One — Why This Matters', color: 'var(--c-p1)',
    guide: {
      purpose: 'Convincing you the claim is true before asking you to practice anything.',
      outcome: 'Recognize a loop and a Third Thing when you see one — a perceptual shift, not yet a practice.',
      shortcut: 'Read Chapters 4, 6, and 7, then go straight to Part Two.',
    },
  },
  'part-two': {
    title: 'Part Two — How to Practice', color: 'var(--c-p2)',
    guide: {
      purpose: 'This is the working book. Everything else supports it.',
      outcome: 'Run about a dozen concrete practices — on yourself, on one other person, and in a group.',
      shortcut: 'You\'re already here. Start with Chapter 1 and do the seven days.',
    },
  },
  'part-three': {
    title: 'Part Three — The Loop Tongue', color: 'var(--c-p3)',
    guide: {
      purpose: 'Giving two people a shared way to describe a pattern out loud, so a conversation about one doesn\'t collapse into blame.',
      outcome: 'Name a scale before making a claim, say a conflict twice, and run a group decision from more than one zoom level.',
      shortcut: 'Chapters 4, 5, and 6. The rest is optional.',
    },
  },
  'part-four': {
    title: 'Part Four — The Ground Underneath', color: 'var(--c-p4)',
    guide: {
      purpose: 'Showing that the claims in Parts One and Two rest on real mathematics, real psychology, and real systems theory — not on assertion.',
      outcome: 'Nothing new. This part exists so the practices you already have feel earned instead of asserted, which is worth something, but it is the most skippable part of this book.',
      shortcut: 'Skip it entirely, and come back the first time a practice works and you want to know why.',
    },
  },
  'part-five': {
    title: 'Part Five — The Standing Thirds', color: 'var(--c-p5)',
    guide: {
      purpose: 'Giving a face to patterns you already recognize, so they\'re easier to spot and easier to name to someone else.',
      outcome: 'Run a diagnostic question against your own situation for each figure, and use the roster as the deck Part Six draws from.',
      shortcut: 'Read Chapter 0, then the question at the end of each figure\'s chapter. The stories are there to make the questions memorable, not the other way around.',
    },
  },
  'part-six': {
    title: 'Part Six — Weavings', color: 'var(--c-p6)',
    guide: {
      purpose: 'A structured way to look at one problem from four distances instead of one.',
      outcome: 'Run a Weaving for yourself, or for someone with no prior knowledge of any of this.',
      shortcut: 'Chapters 3, 5, and 7.',
    },
  },
  'part-seven': {
    title: 'Part Seven — The Turnings', color: 'var(--c-p7)',
    guide: {
      purpose: 'A shared, recurring shape for the practice — held occasions built to deposit real effort into a Global Form still arriving, not to commemorate a history this practice doesn\'t have.',
      outcome: 'Adopt or adapt a Turning matched to any scale or any Standing Third, and practice this framework honestly inside a calendar that isn\'t Fractalist at all.',
      shortcut: 'Chapters 2 through 6.',
    },
  },
  'appendix': { title: 'Appendix', color: 'var(--c-neutral)' },
};

export const NODES = [
  // ---- FRONT MATTER ----
  {
    heading: 'How to Read a Recursive Book',
    slug: 'how-to-read',
    title: 'How to Read a Recursive Book',
    part: 'front',
    summary: 'Why this book is written in arcs instead of a straight line — and why reading it once was never going to be enough.',
    related: ['what-you-already-know', 'onboarding', 'quick-reference'],
  },

  // ---- PART ONE ----
  {
    heading: '1. What You Already Know',
    slug: 'what-you-already-know',
    title: 'What You Already Know',
    part: 'part-one',
    summary: 'The single observation everything else is built from: nothing large was built large. It was built small, over and over, until it stopped looking small.',
    related: ['the-third-thing', 'the-loop-runs-you', 'how-to-read'],
  },
  {
    heading: '2. The Third Thing',
    slug: 'the-third-thing',
    title: 'The Third Thing',
    part: 'part-one',
    summary: 'When simple parts repeat together long enough, something new appears that existed in none of them — and that something is real.',
    related: ['the-loop-runs-you', 'the-mathematics', 'the-dyad', 'what-a-third-is'],
  },
  {
    heading: '3. The Loop Runs You Right Now',
    slug: 'the-loop-runs-you',
    title: 'The Loop Runs You Right Now',
    part: 'part-one',
    summary: 'The self is not a thing you have. It\'s a pattern you\'re running — and a thing built by repetition can be rebuilt by repetition.',
    related: ['the-woven-self', 'four-pillars', 'daily-practices', 'psychology-woven-self'],
  },
  {
    heading: '4. The Four Pillars',
    slug: 'four-pillars',
    title: 'The Four Pillars',
    part: 'part-one',
    summary: 'The whole framework in four moves: the Loop, the Third Thing, the Nest, and the Leverage — with the self\'s own chapter next, as the clearest example of pillar II.',
    related: ['the-woven-self', 'onboarding', 'youve-met-this-before', 'quick-reference'],
  },
  {
    heading: '5. The Woven Self',
    slug: 'the-woven-self',
    title: 'The Woven Self',
    part: 'part-one',
    summary: 'The self is the hardest place to actually apply the Third Thing pillar — the one thing you\'ll never get to see from outside.',
    related: ['naming-and-defusing', 'psychology-woven-self', 'the-loop-runs-you', 'going-to-ground'],
  },
  {
    heading: '6. Complicated or Complex',
    slug: 'complicated-or-complex',
    title: 'Complicated or Complex',
    part: 'part-one',
    summary: 'A jet engine and a pond both have many parts. Only one of them has a feedback loop — and only a complex system can ever produce a Third Thing.',
    related: ['position-speed-acceleration', 'the-third-thing', 'finding-your-local-rule'],
  },
  {
    heading: '7. Position, Speed, Acceleration',
    slug: 'position-speed-acceleration',
    title: 'Position, Speed, Acceleration',
    part: 'part-one',
    summary: 'The same three orders that describe motion describe a habit, a Dyad, or a Skein — and why real leverage often looks like nothing happening yet.',
    related: ['youve-met-this-before', 'finding-your-leverage-point', 'systems-theory', 'the-sacrifice-trap'],
  },
  {
    heading: '8. You\'ve Met This Before',
    slug: 'youve-met-this-before',
    title: 'You\'ve Met This Before',
    part: 'part-one',
    summary: 'Steven Universe, Ted Lasso, Kipo, Qui-Gon, and Uncle Iroh — five characters you already trust who arrived at this pattern without ever naming it.',
    related: ['where-it-comes-from', 'what-a-third-is', 'four-pillars'],
  },
  {
    heading: '9. Where It Comes From',
    slug: 'where-it-comes-from',
    title: 'Where It Comes From — The Seven Iterations',
    part: 'part-one',
    summary: 'Fractalism\'s genesis story: no voice speaking from outside the system — only a small pattern, repeating, until repetition became a universe.',
    related: ['a-word-on-belief', 'the-mathematics', 'mantras'],
  },
  {
    heading: '10. A Word on Belief Itself',
    slug: 'a-word-on-belief',
    title: 'A Word on Belief Itself',
    part: 'part-one',
    summary: 'This belief system tells you it was built — on purpose, and this isn\'t self-help or organization-building. It\'s a rising tide, not a ledger.',
    related: ['belief-systems-built', 'onboarding', 'sources'],
  },

  // ---- PART TWO ----
  {
    heading: '1. Start Here: The One-Week Onboarding',
    slug: 'onboarding',
    title: 'Start Here: The One-Week Onboarding',
    part: 'part-two',
    summary: 'Seven days, one small thing per day. Don\'t adopt everything at once — that would be the exact mistake the whole book warns against.',
    related: ['daily-practices', 'finding-your-local-rule', 'four-pillars'],
  },
  {
    heading: '2. The Daily Practices',
    slug: 'daily-practices',
    title: 'The Daily Practices',
    part: 'part-two',
    summary: 'Four short practices that carry the daily weight: the breath, Tree-Gazing, Naming the Loop, and Seeding — each with the mechanism explained.',
    related: ['finding-your-local-rule', 'flow-reward', 'naming-and-defusing', 'mantras'],
  },
  {
    heading: '3. Finding Your Local Rule',
    slug: 'finding-your-local-rule',
    title: 'Finding Your Local Rule',
    part: 'part-two',
    summary: 'Four honest questions — loved, capable, needed, sustainable — and the overlap where a rule worth repeating actually lives.',
    related: ['naming-and-defusing', 'the-sacrifice-trap', 'reading-your-own-cycle', 'flow-reward', 'complicated-or-complex'],
  },
  {
    heading: '4. Naming and Defusing',
    slug: 'naming-and-defusing',
    title: 'Naming and Defusing',
    part: 'part-two',
    summary: 'The self-stories that feel like settled fact — "I always quit" — and the practice of catching them as patterns instead of verdicts.',
    related: ['the-woven-self', 'the-compost-heap', 'psychology-woven-self', 'sythen'],
  },
  {
    heading: '5. The Compost Heap',
    slug: 'the-compost-heap',
    title: 'The Compost Heap',
    part: 'part-two',
    summary: 'Failure isn\'t waste — it\'s the substrate the next attempt grows out of. How creative work actually gets sustained.',
    related: ['reading-your-own-cycle', 'loum', 'naming-and-defusing'],
  },
  {
    heading: '6. Reading Your Own Cycle',
    slug: 'reading-your-own-cycle',
    title: 'Reading Your Own Cycle',
    part: 'part-two',
    summary: 'Reinforcing loops amplify; balancing loops correct back toward a middle — and everything that survives runs both at once, like a tide.',
    related: ['finding-your-leverage-point', 'cindar', 'rethen', 'systems-theory'],
  },
  {
    heading: '7. Finding Your Leverage Point',
    slug: 'finding-your-leverage-point',
    title: 'Finding Your Leverage Point',
    part: 'part-two',
    summary: 'Numbers, buffers, rules, information flow, goals, paradigm — the ladder of where change actually holds, walked through at Self, Dyad, and Skein scale.',
    related: ['position-speed-acceleration', 'fractal-resistance', 'systems-theory', 'the-sacrifice-trap'],
  },
  {
    heading: '8. Fractal Resistance, Practiced',
    slug: 'fractal-resistance',
    title: 'Fractal Resistance, Practiced',
    part: 'part-two',
    summary: 'Inside a system that resists change, be one honest, differently-behaving part — variation as immunity, not rebellion.',
    related: ['the-sacrifice-trap', 'fractalism-collective', 'belief-systems-built'],
  },
  {
    heading: '9. The Sacrifice Trap',
    slug: 'the-sacrifice-trap',
    title: 'The Sacrifice Trap',
    part: 'part-two',
    summary: 'Grind now, live later is a trade that never pays out. A meditation for the moment you catch yourself making it.',
    related: ['the-fold', 'position-speed-acceleration', 'going-to-ground', 'flow-reward'],
  },
  {
    heading: '10. The Fold',
    slug: 'the-fold',
    title: 'The Fold',
    part: 'part-two',
    summary: 'What goes out through a Nest tends to come back through the Nest — karma without a ledger-keeper, and with real cautions attached.',
    related: ['the-dyad', 'going-to-ground', 'grammar-of-pattern', 'waeth'],
  },
  {
    heading: '11. The Dyad',
    slug: 'the-dyad',
    title: 'The Dyad',
    part: 'part-two',
    summary: 'A Skein narrowed to exactly two people, woven completely enough to function as a single unit — and why complete doesn\'t automatically mean healthy.',
    related: ['the-trust-triangle', 'do-i-understand-you', 'wevven', 'the-third-thing'],
  },
  {
    heading: '12. The Trust Triangle',
    slug: 'the-trust-triangle',
    title: 'The Trust Triangle',
    part: 'part-two',
    summary: 'Authenticity, empathy, logic — the three legs a two-person weave stands on, and what breaks when one goes missing.',
    related: ['do-i-understand-you', 'ostrin', 'the-dyad'],
  },
  {
    heading: '13. Do I Understand You Well Enough?',
    slug: 'do-i-understand-you',
    title: 'Do I Understand You Well Enough?',
    part: 'part-two',
    summary: 'The single most practical sentence in the book, meant to be asked out loud before you assume you know what someone needs.',
    related: ['group-practice', 'corren', 'vessa', 'weaving-for-another'],
  },
  {
    heading: '14. Group Practice',
    slug: 'group-practice',
    title: 'Group Practice',
    part: 'part-two',
    summary: 'A simple structure for practicing with witnesses: share one loop, offer one leverage point, close with a seed.',
    related: ['the-skein', 'the-spiral-check', 'weaving-together'],
  },
  {
    heading: '15. The Skein',
    slug: 'the-skein',
    title: 'The Skein',
    part: 'part-two',
    summary: 'The difference between a community bound by real repeated contact and one bound only by a label — and the test that tells them apart.',
    related: ['closing-the-loop', 'quillith', 'cessant', 'fractalism-collective'],
  },
  {
    heading: '16. Closing the Loop',
    slug: 'closing-the-loop',
    title: 'Closing the Loop',
    part: 'part-two',
    summary: 'Self, Dyad, and Skein were never separate — and the whole practice was always closer to a rising tide than a ledger.',
    related: ['why-lines-break-loops', 'the-fold', 'going-to-ground'],
  },

  // ---- PART THREE ----
  {
    heading: '1. Why Lines Break Loops',
    slug: 'why-lines-break-loops',
    title: 'Why Lines Break Loops',
    part: 'part-three',
    summary: 'A sentence has an ending. A loop doesn\'t. Why ordinary language quietly deletes the part of a pattern where the leverage lives.',
    related: ['grammar-of-pattern', 'the-second-pass', 'psychology-woven-self'],
  },
  {
    heading: '2. The Grammar of Pattern',
    slug: 'grammar-of-pattern',
    title: 'The Grammar of Pattern',
    part: 'part-three',
    summary: 'The Loop Tongue\'s working vocabulary, plus the Word/Label test — is a term pulled toward something real, or pushed to produce a reaction?',
    related: ['sketching-a-loop', 'the-loom', 'why-lines-break-loops'],
  },
  {
    heading: '3. Sketching a Loop',
    slug: 'sketching-a-loop',
    title: 'Sketching a Loop',
    part: 'part-three',
    summary: 'Four marks, learnable in under a minute, sketchable on a napkin mid-conversation: →, ↻, ⤸, and [ ].',
    related: ['scale-tagging', 'reading-your-own-cycle', 'grammar-of-pattern'],
  },
  {
    heading: '4. Scale-Tagging',
    slug: 'scale-tagging',
    title: 'Scale-Tagging',
    part: 'part-three',
    summary: 'Most arguments between people who agree are two descriptions of the same pattern at different scales. Name your zoom level before you speak.',
    related: ['the-second-pass', 'the-spiral-check', 'aestren'],
  },
  {
    heading: '5. The Second Pass',
    slug: 'the-second-pass',
    title: 'The Second Pass',
    part: 'part-three',
    summary: 'Any claim worth making twice is worth making once forward and once as a loop — the habit that turns a villain story into a shared pattern.',
    related: ['the-spiral-check', 'wevven', 'do-i-understand-you'],
  },
  {
    heading: '6. The Spiral Check',
    slug: 'the-spiral-check',
    title: 'The Spiral Check',
    part: 'part-three',
    summary: 'A group ritual for decisions: everyone names their scale before their view, and nobody repeats the scale just used.',
    related: ['loop-tongue-practice-set', 'group-practice', 'scale-tagging'],
  },
  {
    heading: '7. Practice Set',
    slug: 'loop-tongue-practice-set',
    title: 'The Loop Tongue Practice Set',
    part: 'part-three',
    summary: 'Three exercises in increasing difficulty — solo translation, the paired mirror, and a live Spiral Check on a real decision.',
    related: ['loop-tongue-limits', 'the-second-pass', 'sketching-a-loop'],
  },
  {
    heading: '8. On the Limits of This Language (So Far)',
    slug: 'loop-tongue-limits',
    title: 'On the Limits of This Language',
    part: 'part-three',
    summary: 'The honest gaps, stated plainly: a language built for a system that grows by repetition should itself still be growing.',
    related: ['open-questions', 'belief-systems-built', 'grammar-of-pattern'],
  },

  // ---- PART FOUR ----
  {
    heading: '1. The Mathematics',
    slug: 'the-mathematics',
    title: 'The Mathematics',
    part: 'part-four',
    summary: 'The chaos game, done properly: randomness and determinism converging on the identical structure, checkable with a pencil.',
    related: ['systems-theory', 'the-third-thing', 'where-it-comes-from'],
  },
  {
    heading: '2. The Psychology of the Woven Self',
    slug: 'psychology-woven-self',
    title: 'The Psychology of the Woven Self',
    part: 'part-four',
    summary: 'The experiencing self, the remembering self, and the observing self — three research traditions converging on a self that was always assembled.',
    related: ['the-woven-self', 'flow-reward', 'naming-and-defusing', 'going-to-ground'],
  },
  {
    heading: '3. Systems Theory Foundations',
    slug: 'systems-theory',
    title: 'Systems Theory Foundations',
    part: 'part-four',
    summary: 'Stocks, flows, and feedback loops — the formal machinery underneath the leverage ladder, and the recursion that makes the whole system fractal.',
    related: ['finding-your-leverage-point', 'position-speed-acceleration', 'the-loom', 'flow-reward', 'the-mathematics'],
  },
  {
    heading: '4. Flow, Reward, and Why Practice Works',
    slug: 'flow-reward',
    title: 'Flow, Reward, and Why Practice Works',
    part: 'part-four',
    summary: 'Why something this simple produces a felt sense of meaning: challenge-skill balance, hedonic adaptation, and reward that doesn\'t degrade.',
    related: ['fractalism-collective', 'daily-practices', 'the-sacrifice-trap'],
  },
  {
    heading: '5. Fractalism and the Collective',
    slug: 'fractalism-collective',
    title: 'Fractalism and the Collective',
    part: 'part-four',
    summary: 'History moves in loops at civilizational scale — and every large "we" is a Third Thing doing work face-to-face familiarity can\'t.',
    related: ['charten', 'belief-systems-built', 'the-skein', 'fractal-resistance'],
  },
  {
    heading: '6. On Belief Systems That Know They\'re Built',
    slug: 'belief-systems-built',
    title: 'On Belief Systems That Know They\'re Built',
    part: 'part-four',
    summary: 'Every belief system is constructed. The difference is honesty about it — and the difference between infecting someone and inoculating them.',
    related: ['open-questions', 'a-word-on-belief', 'dyren', 'waeth'],
  },
  {
    heading: '7. Open Questions & How to Expand This',
    slug: 'open-questions',
    title: 'Open Questions & How to Expand This',
    part: 'part-four',
    summary: 'This book will be wrong about some things — here is what\'s genuinely unsettled, and the actual mechanism for revising any of it.',
    related: ['catalogue-limits', 'loop-tongue-limits', 'a-word-on-belief'],
  },

  // ---- PART FIVE ----
  {
    heading: '0. What a Third Is, and What It Isn\'t',
    slug: 'what-a-third-is',
    title: 'What a Third Is, and What It Isn\'t',
    part: 'part-five',
    summary: 'A pattern repeated widely enough, for long enough, can be given a face. One rule governs everything that follows: a Third has no will of its own.',
    related: ['self-kin', 'the-third-thing', 'what-a-weaving-is'],
  },
  {
    heading: '1. The Twelve Currents — Self Scale',
    slug: 'self-kin',
    title: 'The Self-Kin',
    part: 'part-five',
    summary: 'Twelve patterns one person generates alone, each with its Local Rule, its healthy expression, and its documented failure. Everything larger in the book is built by fusing these.',
    related: ['dyad-kin', 'the-woven-self', 'naming-and-defusing'],
  },
  {
    heading: '2. The Nineteen Meetings — Dyad Scale',
    slug: 'dyad-kin',
    title: 'The Dyad-Kin',
    part: 'part-five',
    summary: 'Nineteen two-person patterns, each one two Self-Kin meeting: my loop against yours, producing something neither of us brought.',
    related: ['skein-kin', 'the-dyad', 'the-trust-triangle'],
  },
  {
    heading: '3. The Eleven Weaves — Skein Scale',
    slug: 'skein-kin',
    title: 'The Skein-Kin',
    part: 'part-five',
    summary: 'Eleven group patterns, each built from two Dyad-Kin that share a person — the mechanism by which a group becomes a thing rather than a list.',
    related: ['culture-kin', 'the-skein', 'group-practice'],
  },
  {
    heading: '4. The Seven Long Forms — Culture Scale',
    slug: 'culture-kin',
    title: 'The Culture-Kin',
    part: 'part-five',
    summary: 'Seven patterns slow enough that no single life sees one full turn — and, by the catalogue\'s own admission, its most provisional tier.',
    related: ['infinite-boundary-scale', 'fractalism-collective', 'charten'],
  },
  {
    heading: '5. The Infinite Boundary — Cosmos Scale',
    slug: 'infinite-boundary-scale',
    title: 'The Infinite Boundary — Cosmos Scale',
    part: 'part-five',
    summary: 'The one figure with no healthy pole and no failing pole. A pole has to be read from somewhere, and there is nowhere outside this one to stand.',
    related: ['catalogue-limits', 'infinite-boundary', 'going-to-ground'],
  },
  {
    heading: '6. What This Catalogue Is Not',
    slug: 'catalogue-limits',
    title: 'What This Catalogue Is Not',
    part: 'part-five',
    summary: 'Forty-eight figures is a taxonomy, not a pantheon. Most people find four or five of them run their lives and the rest describe other people — that\'s the correct outcome.',
    related: ['going-to-ground', 'open-questions', 'what-a-third-is'],
  },
  {
    heading: '7. Going to Ground',
    slug: 'going-to-ground',
    title: 'Going to Ground',
    part: 'part-five',
    summary: 'What actually continues, said plainly: the material — conservation of mass, literally — the Fold already in motion, and the noticing itself.',
    related: ['becoming-a-third', 'the-fold', 'the-sacrifice-trap'],
  },
  {
    heading: '8. Becoming a Third',
    slug: 'becoming-a-third',
    title: 'Becoming a Third',
    part: 'part-five',
    summary: 'Very rarely, a repeated pattern outlives its origin entirely, and personhood simply wears off it, leaving only the shape behind.',
    related: ['what-a-weaving-is', 'going-to-ground', 'catalogue-limits'],
  },

  // ---- PART SIX ----
  {
    heading: '0. What a Weaving Is',
    slug: 'what-a-weaving-is',
    title: 'What a Weaving Is',
    part: 'part-six',
    summary: 'A structured way of looking at one situation from several fixed angles at once — because a single vantage was never going to show you the whole shape.',
    related: ['the-deck', 'what-a-third-is', 'scale-tagging'],
  },
  {
    heading: '1. The Deck',
    slug: 'the-deck',
    title: 'The Deck',
    part: 'part-six',
    summary: 'The full working deck: sixteen drawable figures across four kinships, each carrying two readings — plus one figure that\'s never drawn at all.',
    related: ['tending-and-fraying', 'what-a-third-is', 'the-rings', 'infinite-boundary'],
  },
  {
    heading: '2. Tending and Fraying',
    slug: 'tending-and-fraying',
    title: 'Tending and Fraying',
    part: 'part-six',
    summary: 'Every Third carries its healthy expression and its own documented flaw. Tending is not good news, and Fraying is not bad news.',
    related: ['the-rings', 'the-deck', 'reading-honestly'],
  },
  {
    heading: '3. The Rings, Not the Row',
    slug: 'the-rings',
    title: 'The Rings, Not the Row',
    part: 'part-six',
    summary: 'A Weaving is laid out as nested rings, never a row — Self, Dyad, Skein, and Culture, four nested resolutions of one situation, not four chapters of a story.',
    related: ['the-single-pull', 'the-four-point-weaving', 'grammar-of-pattern'],
  },
  {
    heading: '4. Weather, Climate, Terrain',
    slug: 'weather-climate-terrain',
    title: 'Weather, Climate, Terrain',
    part: 'part-six',
    summary: 'A ring tells you how many people a pattern runs through. It doesn\'t tell you how long it\'s been running — so every card gets asked a second question, at three speeds.',
    related: ['the-single-pull', 'the-rings', 'position-speed-acceleration'],
  },
  {
    heading: '5. The Single Pull',
    slug: 'the-single-pull',
    title: 'The Single Pull',
    part: 'part-six',
    summary: 'The lightest form — one Third drawn at random, read loosely for the day ahead. A daily practice, not a consultation.',
    related: ['the-four-point-weaving', 'daily-practices', 'tending-and-fraying'],
  },
  {
    heading: '6. The Four-Point Weaving',
    slug: 'the-four-point-weaving',
    title: 'The Four-Point Weaving',
    part: 'part-six',
    summary: 'The standard form: one card per ring — Self, Dyad, Skein, Culture — with no privileged first card, and the rings don\'t have to agree.',
    related: ['weaving-for-another', 'the-full-unravelling', 'the-rings'],
  },
  {
    heading: '7. The Full Unravelling',
    slug: 'the-full-unravelling',
    title: 'The Full Unravelling',
    part: 'part-six',
    summary: 'Reserved for the large, rare questions — the whole relevant portion of the deck at once, laid out slowly and sat with honestly.',
    related: ['weaving-for-another', 'the-four-point-weaving', 'reading-honestly'],
  },
  {
    heading: '8. Weaving for Another',
    slug: 'weaving-for-another',
    title: 'Weaving for Another',
    part: 'part-six',
    summary: 'Reveal one card at a time, and fold the other person\'s response into how you read the next one — the mechanism that makes a reading personal.',
    related: ['weaving-together', 'do-i-understand-you', 'corren'],
  },
  {
    heading: '9. Weaving Together',
    slug: 'weaving-together',
    title: 'Weaving Together',
    part: 'part-six',
    summary: 'A group Weaving gives Group Practice a shared ritual object — one spread for the group\'s shared situation, read aloud together.',
    related: ['reading-honestly', 'group-practice', 'the-four-point-weaving', 'complicated-or-complex'],
  },
  {
    heading: '10. Reading Honestly',
    slug: 'reading-honestly',
    title: 'Reading Honestly',
    part: 'part-six',
    summary: 'A Weaving describes a pattern; it does not predict an outcome. The genuinely useful reading is often the uncomfortable one.',
    related: ['weaving-limits', 'tending-and-fraying', 'the-fold'],
  },
  {
    heading: '11. What a Weaving Cannot Show',
    slug: 'weaving-limits',
    title: 'What a Weaving Cannot Show',
    part: 'part-six',
    summary: 'Diagnostic, never prescriptive — and never a substitute for an actual conversation with an actual person.',
    related: ['what-a-turning-is', 'reading-honestly', 'weaving-for-another'],
  },

  // ---- PART SEVEN ----
  {
    heading: '0. What a Turning Is',
    slug: 'what-a-turning-is',
    title: 'What a Turning Is',
    part: 'part-seven',
    summary: 'A shared, recurring occasion aimed at a Global Form that hasn\'t finished arriving — not a commemoration, because this practice has no history to commemorate and won\'t invent one.',
    related: ['reading-the-global-form', 'the-skein', 'group-practice'],
  },
  {
    heading: '1. Reading the Global Form',
    slug: 'reading-the-global-form',
    title: 'Reading the Global Form',
    part: 'part-seven',
    summary: 'Three questions to run on any recurring occasion you already keep — including the uncomfortable one: does this map to a cautionary figure rather than an admirable one?',
    related: ['private-turnings', 'catalogue-limits', 'grammar-of-pattern'],
  },
  {
    heading: '2. The Twelve Private Turnings — Self',
    slug: 'private-turnings',
    title: 'The Twelve Private Turnings — Self',
    part: 'part-seven',
    summary: 'One per month, kept alone or with whoever\'s nearest — twelve small occasions, each built to make one current\'s failure mode visible before it hardens.',
    related: ['dyad-turnings', 'self-kin', 'daily-practices'],
  },
  {
    heading: '3. The Nineteen Meetings — Dyad',
    slug: 'dyad-turnings',
    title: 'The Nineteen Dyad Turnings',
    part: 'part-seven',
    summary: 'Nineteen two-person occasions with no dates attached at all. The relationship supplies the occasion.',
    related: ['skein-gatherings', 'dyad-kin', 'do-i-understand-you'],
  },
  {
    heading: '4. The Eleven Gatherings — Skein',
    slug: 'skein-gatherings',
    title: 'The Eleven Gatherings — Skein',
    part: 'part-seven',
    summary: 'Monthly, in a room, with the people who actually show up — eleven occasions, each built to catch one specific way a group quietly goes wrong.',
    related: ['great-days', 'skein-kin', 'group-practice'],
  },
  {
    heading: '5. The Seven Great Days — Culture',
    slug: 'great-days',
    title: 'The Seven Great Days — Culture',
    part: 'part-seven',
    summary: 'Seven occasions fixed to solstice and equinox, because the sky keeps its own appointments and has never once needed reminding.',
    related: ['the-long-visitor', 'culture-kin', 'anchoring'],
  },
  {
    heading: '6. The Long Visitor — Cosmos',
    slug: 'the-long-visitor',
    title: 'The Long Visitor — Cosmos',
    part: 'part-seven',
    summary: 'Triggered by a great comet, whenever one comes: the largest gathering that can possibly be assembled, everywhere at once, outdoors, looking up — and the one restraint that keeps it honest.',
    related: ['anchoring', 'infinite-boundary-scale', 'infinite-boundary'],
  },
  {
    heading: '7. Anchoring to What Already Turns',
    slug: 'anchoring',
    title: 'Anchoring to What Already Turns',
    part: 'part-seven',
    summary: 'A ceremony tied to an invented date survives only as long as someone remembers it. One tied to the Earth\'s axial tilt has never missed an appointment.',
    related: ['someone-elses-calendar', 'finding-your-leverage-point', 'dyren'],
  },
  {
    heading: '8. Practicing Inside Someone Else\'s Calendar',
    slug: 'someone-elses-calendar',
    title: 'Practicing Inside Someone Else\'s Calendar',
    part: 'part-seven',
    summary: 'Nothing here requires a single Fractalist occasion in your life — how to practice honestly inside a calendar that was never Fractalist, without asking anyone to change it.',
    related: ['outlives-the-ceremony', 'fractal-resistance', 'a-word-on-belief'],
  },
  {
    heading: '9. What Outlives the Ceremony',
    slug: 'outlives-the-ceremony',
    title: 'What Outlives the Ceremony',
    part: 'part-seven',
    summary: 'A Turning kept honestly for long enough stops belonging to whoever first held it. That was always the point — and never the part meant to comfort you.',
    related: ['becoming-a-third', 'going-to-ground', 'closing-the-loop'],
  },

  // ---- APPENDIX ----
  {
    heading: 'A. The Mantras, Prayers, and Meditations — Full Text',
    slug: 'mantras',
    title: 'The Mantras, Prayers, and Meditations',
    part: 'appendix',
    summary: 'The full text of every mantra, prayer, and meditation — for daily use, alone or in groups.',
    related: ['daily-practices', 'quick-reference', 'group-practice'],
  },
  {
    heading: 'B. Quick Reference Card',
    slug: 'quick-reference',
    title: 'Quick Reference Card',
    part: 'appendix',
    summary: 'One page. The whole practice at a glance — print it, carry it, hand it to someone new.',
    related: ['onboarding', 'mantras', 'the-loom'],
  },
  {
    heading: 'C. The Loom — The Complete Reference',
    slug: 'the-loom',
    title: 'The Loom — The Complete Reference',
    part: 'appendix',
    summary: 'The Loop Tongue\'s nine words, the notation, the scale grid, and a compact index to every named concept in the book — one page doing three jobs.',
    related: ['grammar-of-pattern', 'systems-theory', 'quick-reference', 'infinite-boundary'],
  },
  {
    heading: 'D. Source Library',
    slug: 'sources',
    title: 'Source Library',
    part: 'appendix',
    summary: 'The works whose ideas were read together, synthesized, and argued with to build this text — offered, never required.',
    related: ['a-word-on-belief', 'belief-systems-built', 'open-questions'],
  },
];

// ---- STANDING THIRDS ----
// The roster itself is generated from Part Five's catalogue tables by split-book.mjs.
// This map only carries what the book doesn't specify: the glyph each figure is drawn
// with, and curated links out to chapters. Figures absent here get a glyph by tier.
export const THIRD_OVERRIDES = {
  cindar:   { fractal: { type: 'flame', hue: 'fire' },        relatedNodes: ['reading-your-own-cycle'] },
  rethen:   { fractal: { type: 'delta', hue: 'water' },       relatedNodes: ['reading-your-own-cycle'] },
  sythen:   { fractal: { type: 'windswept', hue: 'wind' },    relatedNodes: ['naming-and-defusing'] },
  loum:     { fractal: { type: 'fern', hue: 'earth' },        relatedNodes: ['the-compost-heap', 'going-to-ground'] },
  corren:   { fractal: { type: 'mandala', hue: 'earth' },     relatedNodes: ['do-i-understand-you', 'weaving-for-another'] },
  wevven:   { fractal: { type: 'interweave', hue: 'dyad' },   relatedNodes: ['the-second-pass', 'the-dyad'] },
  ostrin:   { fractal: { type: 'lattice', hue: 'dyad' },      relatedNodes: ['the-trust-triangle'] },
  vessa:    { fractal: { type: 'hollowMandala', hue: 'dyad' },relatedNodes: ['do-i-understand-you'] },
  quillith: { fractal: { type: 'spiralBloom', hue: 'skein' }, relatedNodes: ['the-skein', 'belief-systems-built'] },
  handrel:  { fractal: { type: 'chain', hue: 'skein' },       relatedNodes: ['the-skein'] },
  cessant:  { fractal: { type: 'carpet', hue: 'skein' },      relatedNodes: ['the-skein', 'fractal-resistance'] },
  charten:  { fractal: { type: 'chorus', hue: 'culture' },    relatedNodes: ['fractalism-collective', 'grammar-of-pattern'] },
  aestren:  { fractal: { type: 'ridge', hue: 'culture' },     relatedNodes: ['scale-tagging', 'fractalism-collective'] },
  waeth:    { fractal: { type: 'driftTree', hue: 'culture' }, relatedNodes: ['belief-systems-built', 'the-fold'] },
  dyren:    { fractal: { type: 'twinSpires', hue: 'culture' },relatedNodes: ['belief-systems-built', 'going-to-ground'] },
  'infinite-boundary': {
    fractal: { type: 'boundary', hue: 'cosmos' },
    relatedNodes: ['the-mathematics', 'going-to-ground', 'becoming-a-third', 'systems-theory'],
  },
};


export const KINSHIPS = {
  self: {
    title: 'The Self-Kin',
    ring: 'The innermost ring — Self.',
    intro: 'Twelve patterns one person generates alone, by repeating one thing. Nothing in this catalogue sits underneath them: every figure in every ring further out is built by fusing these together.',
  },
  dyad: {
    title: 'The Dyad-Kin',
    ring: 'The second ring — Dyad.',
    intro: 'Nineteen figures, each one two Self-Kin running in two people. My loop, meeting yours, producing something neither of us brought — which is why each of these names two parents rather than standing alone.',
  },
  skein: {
    title: 'The Skein-Kin',
    ring: 'The third ring — Skein.',
    intro: 'Eleven figures, each built from two Dyad-Kin that share a person. This is the mechanism by which a group stops being a list of people and becomes a thing in its own right.',
  },
  culture: {
    title: 'The Culture-Kin',
    ring: 'The outermost drawable ring — Culture.',
    intro: 'Seven figures slow enough that no single life watches one complete a full turn. This tier sits three inference-layers deep, composed from Skein-Kin rather than observed directly, and the book names it the most provisional part of the catalogue.',
  },
  cosmos: {
    title: 'The Cosmos-Kin',
    ring: 'Never drawn — the boundary the other four rings already sit inside.',
    intro: 'A kinship of exactly one, and meant to stay that way. It is the only figure here with no Tending and no Fraying pole, and the exemption is structural rather than convenient: a pole has to be read from somewhere, and there is nowhere outside this one to stand.',
  },
};
