// Maps every chapter heading in source/Fractalism_Complete.md to a site node.
// `heading` must exactly match the text after "## " in the source.
// `related` is the curated "where next" graph — first entry is the featured next step.
// Summaries double as the hook text shown when another page links here.

export const PARTS = {
  'front': { title: 'Front Matter', color: 'var(--c-neutral)' },
  'part-one': { title: 'Part One — Why This Matters', color: 'var(--c-p1)' },
  'part-two': { title: 'Part Two — How to Practice', color: 'var(--c-p2)' },
  'part-three': { title: 'Part Three — The Loop Tongue', color: 'var(--c-p3)' },
  'part-four': { title: 'Part Four — Deeper Theory', color: 'var(--c-p4)' },
  'part-five': { title: 'Part Five — The Standing Thirds', color: 'var(--c-p5)' },
  'part-six': { title: 'Part Six — Weavings', color: 'var(--c-p6)' },
  'appendix': { title: 'Appendix', color: 'var(--c-neutral)' },
};

export const NODES = [
  // ---- FRONT MATTER ----
  {
    heading: 'How to Read a Recursive Book',
    slug: 'how-to-read',
    title: 'How to Read a Recursive Book',
    part: 'front',
    summary: 'Why this book is written in arcs instead of a straight line — and why reading it once was never going to be enough.',
    related: ['what-you-already-know', 'onboarding', 'quick-reference'],
  },

  // ---- PART ONE ----
  {
    heading: '1. What You Already Know',
    slug: 'what-you-already-know',
    title: 'What You Already Know',
    part: 'part-one',
    summary: 'The single observation everything else is built from: nothing large was built large. It was built small, over and over, until it stopped looking small.',
    related: ['the-third-thing', 'the-loop-runs-you', 'how-to-read'],
  },
  {
    heading: '2. The Third Thing',
    slug: 'the-third-thing',
    title: 'The Third Thing',
    part: 'part-one',
    summary: 'When simple parts repeat together long enough, something new appears that existed in none of them — and that something is real.',
    related: ['the-loop-runs-you', 'the-mathematics', 'the-dyad', 'what-a-third-is'],
  },
  {
    heading: '3. The Loop Runs You Right Now',
    slug: 'the-loop-runs-you',
    title: 'The Loop Runs You Right Now',
    part: 'part-one',
    summary: 'The self is not a thing you have. It\'s a pattern you\'re running — and a thing built by repetition can be rebuilt by repetition.',
    related: ['four-pillars', 'daily-practices', 'psychology-woven-self', 'reading-your-own-cycle'],
  },
  {
    heading: '4. The Four Pillars',
    slug: 'four-pillars',
    title: 'The Four Pillars',
    part: 'part-one',
    summary: 'The whole framework in four moves: the Loop, the Third Thing, the Woven Self, and the Fertile Field.',
    related: ['onboarding', 'youve-met-this-before', 'quick-reference'],
  },
  {
    heading: '5. You\'ve Met This Before',
    slug: 'youve-met-this-before',
    title: 'You\'ve Met This Before',
    part: 'part-one',
    summary: 'Steven Universe, Ted Lasso, Kipo, Qui-Gon, and Uncle Iroh — five characters you already trust who arrived at this pattern without ever naming it.',
    related: ['where-it-comes-from', 'what-a-third-is', 'four-pillars'],
  },
  {
    heading: '6. Where It Comes From',
    slug: 'where-it-comes-from',
    title: 'Where It Comes From — The Seven Iterations',
    part: 'part-one',
    summary: 'Fractalism\'s genesis story: no voice speaking from outside the system — only a small pattern, repeating, until repetition became a universe.',
    related: ['a-word-on-belief', 'the-mathematics', 'mantras'],
  },
  {
    heading: '7. A Word on Belief Itself',
    slug: 'a-word-on-belief',
    title: 'A Word on Belief Itself',
    part: 'part-one',
    summary: 'This belief system tells you it was built — on purpose. Why an admitted construction is a stronger kind of honesty, not a weaker kind of truth.',
    related: ['belief-systems-built', 'onboarding', 'sources'],
  },

  // ---- PART TWO ----
  {
    heading: '1. Start Here: The One-Week Onboarding',
    slug: 'onboarding',
    title: 'Start Here: The One-Week Onboarding',
    part: 'part-two',
    summary: 'Seven days, one small thing per day. Don\'t adopt everything at once — that would be the exact mistake the whole book warns against.',
    related: ['daily-practices', 'finding-your-local-rule', 'four-pillars'],
  },
  {
    heading: '2. The Daily Practices',
    slug: 'daily-practices',
    title: 'The Daily Practices',
    part: 'part-two',
    summary: 'Four short practices that carry the daily weight: the breath, Tree-Gazing, Naming the Loop, and Seeding — each with the mechanism explained.',
    related: ['finding-your-local-rule', 'flow-reward', 'naming-and-defusing', 'mantras'],
  },
  {
    heading: '3. Finding Your Local Rule',
    slug: 'finding-your-local-rule',
    title: 'Finding Your Local Rule',
    part: 'part-two',
    summary: 'Four honest questions — loved, capable, needed, sustainable — and the overlap where a rule worth repeating actually lives.',
    related: ['naming-and-defusing', 'the-sacrifice-trap', 'reading-your-own-cycle', 'flow-reward'],
  },
  {
    heading: '4. Naming and Defusing',
    slug: 'naming-and-defusing',
    title: 'Naming and Defusing',
    part: 'part-two',
    summary: 'The self-stories that feel like settled fact — "I always quit" — and the practice of catching them as patterns instead of verdicts.',
    related: ['the-compost-heap', 'psychology-woven-self', 'sythen', 'the-loop-runs-you'],
  },
  {
    heading: '5. The Compost Heap',
    slug: 'the-compost-heap',
    title: 'The Compost Heap',
    part: 'part-two',
    summary: 'Failure isn\'t waste — it\'s the substrate the next attempt grows out of. How creative work actually gets sustained.',
    related: ['reading-your-own-cycle', 'loum', 'naming-and-defusing'],
  },
  {
    heading: '6. Reading Your Own Cycle',
    slug: 'reading-your-own-cycle',
    title: 'Reading Your Own Cycle',
    part: 'part-two',
    summary: 'Reinforcing loops amplify; balancing loops correct back toward a middle. Learn which one you\'re actually running before you try to change it.',
    related: ['finding-your-leverage-point', 'cindar', 'rethen', 'systems-theory'],
  },
  {
    heading: '7. Finding Your Leverage Point',
    slug: 'finding-your-leverage-point',
    title: 'Finding Your Leverage Point',
    part: 'part-two',
    summary: 'Numbers, buffers, rules, information flow, goals, paradigm — the ladder of where change actually holds, from weakest lever to strongest.',
    related: ['fractal-resistance', 'systems-theory', 'the-sacrifice-trap'],
  },
  {
    heading: '8. Fractal Resistance, Practiced',
    slug: 'fractal-resistance',
    title: 'Fractal Resistance, Practiced',
    part: 'part-two',
    summary: 'Inside a system that resists change, be one honest, differently-behaving part — variation as immunity, not rebellion.',
    related: ['the-sacrifice-trap', 'fractalism-collective', 'belief-systems-built'],
  },
  {
    heading: '9. The Sacrifice Trap',
    slug: 'the-sacrifice-trap',
    title: 'The Sacrifice Trap',
    part: 'part-two',
    summary: 'Grind now, live later is a trade that never pays out. A meditation for the moment you catch yourself making it.',
    related: ['the-fold', 'going-to-ground', 'flow-reward'],
  },
  {
    heading: '10. The Fold',
    slug: 'the-fold',
    title: 'The Fold',
    part: 'part-two',
    summary: 'What goes out through a Nest tends to come back through the Nest — karma without a ledger-keeper, and with real cautions attached.',
    related: ['the-dyad', 'going-to-ground', 'grammar-of-pattern', 'waeth'],
  },
  {
    heading: '11. The Dyad',
    slug: 'the-dyad',
    title: 'The Dyad',
    part: 'part-two',
    summary: 'A Skein narrowed to exactly two people, woven completely enough to function as a single unit — and why complete doesn\'t automatically mean healthy.',
    related: ['the-trust-triangle', 'do-i-understand-you', 'wevven', 'the-third-thing'],
  },
  {
    heading: '12. The Trust Triangle',
    slug: 'the-trust-triangle',
    title: 'The Trust Triangle',
    part: 'part-two',
    summary: 'Authenticity, empathy, logic — the three legs a two-person weave stands on, and what breaks when one goes missing.',
    related: ['do-i-understand-you', 'ostrin', 'the-dyad'],
  },
  {
    heading: '13. Do I Understand You Well Enough?',
    slug: 'do-i-understand-you',
    title: 'Do I Understand You Well Enough?',
    part: 'part-two',
    summary: 'The single most practical sentence in the book, meant to be asked out loud before you assume you know what someone needs.',
    related: ['group-practice', 'corren', 'vessa', 'weaving-for-another'],
  },
  {
    heading: '14. Group Practice',
    slug: 'group-practice',
    title: 'Group Practice',
    part: 'part-two',
    summary: 'A simple structure for practicing with witnesses: share one loop, offer one leverage point, close with a seed.',
    related: ['the-skein', 'the-spiral-check', 'weaving-together'],
  },
  {
    heading: '15. The Skein',
    slug: 'the-skein',
    title: 'The Skein',
    part: 'part-two',
    summary: 'The difference between a community bound by real repeated contact and one bound only by a label — and the test that tells them apart.',
    related: ['closing-the-loop', 'quillith', 'cessant', 'fractalism-collective'],
  },
  {
    heading: '16. Closing the Loop',
    slug: 'closing-the-loop',
    title: 'Closing the Loop',
    part: 'part-two',
    summary: 'Self, Dyad, and Skein were never separate — and suffering, held honestly, is the friction that reveals what was invisible.',
    related: ['why-lines-break-loops', 'the-fold', 'going-to-ground'],
  },

  // ---- PART THREE ----
  {
    heading: '1. Why Lines Break Loops',
    slug: 'why-lines-break-loops',
    title: 'Why Lines Break Loops',
    part: 'part-three',
    summary: 'A sentence has an ending. A loop doesn\'t. Why ordinary language quietly deletes the part of a pattern where the leverage lives.',
    related: ['grammar-of-pattern', 'the-second-pass', 'psychology-woven-self'],
  },
  {
    heading: '2. The Grammar of Pattern',
    slug: 'grammar-of-pattern',
    title: 'The Grammar of Pattern',
    part: 'part-three',
    summary: 'The Loop Tongue\'s working vocabulary — nine words, each earned through practice, deliberately few enough to actually spread.',
    related: ['sketching-a-loop', 'loop-tongue-glossary', 'why-lines-break-loops'],
  },
  {
    heading: '3. Sketching a Loop',
    slug: 'sketching-a-loop',
    title: 'Sketching a Loop',
    part: 'part-three',
    summary: 'Four marks, learnable in under a minute, sketchable on a napkin mid-conversation: →, ↻, ⤸, and [ ].',
    related: ['scale-tagging', 'reading-your-own-cycle', 'grammar-of-pattern'],
  },
  {
    heading: '4. Scale-Tagging',
    slug: 'scale-tagging',
    title: 'Scale-Tagging',
    part: 'part-three',
    summary: 'Most arguments between people who agree are two descriptions of the same pattern at different scales. Name your zoom level before you speak.',
    related: ['the-second-pass', 'the-spiral-check', 'aestren'],
  },
  {
    heading: '5. The Second Pass',
    slug: 'the-second-pass',
    title: 'The Second Pass',
    part: 'part-three',
    summary: 'Any claim worth making twice is worth making once forward and once as a loop — the habit that turns a villain story into a shared pattern.',
    related: ['the-spiral-check', 'wevven', 'do-i-understand-you'],
  },
  {
    heading: '6. The Spiral Check',
    slug: 'the-spiral-check',
    title: 'The Spiral Check',
    part: 'part-three',
    summary: 'A group ritual for decisions: everyone names their scale before their view, and nobody repeats the scale just used.',
    related: ['loop-tongue-practice-set', 'group-practice', 'scale-tagging'],
  },
  {
    heading: '7. Practice Set',
    slug: 'loop-tongue-practice-set',
    title: 'The Loop Tongue Practice Set',
    part: 'part-three',
    summary: 'Three exercises in increasing difficulty — solo translation, the paired mirror, and a live Spiral Check on a real decision.',
    related: ['loop-tongue-limits', 'the-second-pass', 'sketching-a-loop'],
  },
  {
    heading: '8. On the Limits of This Language (So Far)',
    slug: 'loop-tongue-limits',
    title: 'On the Limits of This Language',
    part: 'part-three',
    summary: 'The honest gaps, stated plainly: a language built for a system that grows by repetition should itself still be growing.',
    related: ['open-questions', 'belief-systems-built', 'grammar-of-pattern'],
  },

  // ---- PART FOUR ----
  {
    heading: '1. The Mathematics',
    slug: 'the-mathematics',
    title: 'The Mathematics',
    part: 'part-four',
    summary: 'The chaos game, done properly: randomness and determinism converging on the identical structure, checkable with a pencil.',
    related: ['systems-theory', 'the-third-thing', 'where-it-comes-from'],
  },
  {
    heading: '2. The Psychology of the Woven Self',
    slug: 'psychology-woven-self',
    title: 'The Psychology of the Woven Self',
    part: 'part-four',
    summary: 'The experiencing self, the remembering self, and the observing self — three research traditions converging on a self that was always assembled.',
    related: ['flow-reward', 'naming-and-defusing', 'going-to-ground'],
  },
  {
    heading: '3. Systems Theory Foundations',
    slug: 'systems-theory',
    title: 'Systems Theory Foundations',
    part: 'part-four',
    summary: 'Stocks, flows, and feedback loops — the formal machinery underneath the leverage ladder, and why paradigm change cascades downward.',
    related: ['finding-your-leverage-point', 'flow-reward', 'the-mathematics'],
  },
  {
    heading: '4. Flow, Reward, and Why Practice Works',
    slug: 'flow-reward',
    title: 'Flow, Reward, and Why Practice Works',
    part: 'part-four',
    summary: 'Why something this simple produces a felt sense of meaning: challenge-skill balance, hedonic adaptation, and reward that doesn\'t degrade.',
    related: ['fractalism-collective', 'daily-practices', 'the-sacrifice-trap'],
  },
  {
    heading: '5. Fractalism and the Collective',
    slug: 'fractalism-collective',
    title: 'Fractalism and the Collective',
    part: 'part-four',
    summary: 'History moves in loops at civilizational scale — and every large "we" is a Third Thing doing work face-to-face familiarity can\'t.',
    related: ['belief-systems-built', 'the-skein', 'fractal-resistance'],
  },
  {
    heading: '6. On Belief Systems That Know They\'re Built',
    slug: 'belief-systems-built',
    title: 'On Belief Systems That Know They\'re Built',
    part: 'part-four',
    summary: 'Every belief system is constructed. The difference is honesty about it — and the difference between infecting someone and inoculating them.',
    related: ['open-questions', 'a-word-on-belief', 'dyren', 'waeth'],
  },
  {
    heading: '7. Open Questions & How to Expand This',
    slug: 'open-questions',
    title: 'Open Questions & How to Expand This',
    part: 'part-four',
    summary: 'This book will be wrong about some things — here is what\'s genuinely unsettled, and the actual mechanism for revising any of it.',
    related: ['unnamed-thirds', 'loop-tongue-limits', 'a-word-on-belief'],
  },

  // ---- PART FIVE (non-character chapters) ----
  {
    heading: '0. What a Third Is, and What It Isn\'t',
    slug: 'what-a-third-is',
    title: 'What a Third Is, and What It Isn\'t',
    part: 'part-five',
    summary: 'A pattern repeated widely enough, for long enough, can be given a face. One rule governs everything that follows: a Third has no will of its own.',
    related: ['what-a-weaving-is', 'the-third-thing', 'becoming-a-third'],
  },
  {
    heading: '16. The Unnamed Thirds',
    slug: 'unnamed-thirds',
    title: 'The Unnamed Thirds',
    part: 'part-five',
    summary: 'The roster was never meant to be complete. How to notice a pattern, stand it up, and see whether the name survives being retold.',
    related: ['going-to-ground', 'open-questions', 'what-a-third-is'],
  },
  {
    heading: '17. Going to Ground',
    slug: 'going-to-ground',
    title: 'Going to Ground',
    part: 'part-five',
    summary: 'What actually continues, said plainly: the material, the Fold already in motion, and the noticing itself — unowned, and never scarce.',
    related: ['becoming-a-third', 'the-fold', 'the-sacrifice-trap'],
  },
  {
    heading: '18. Becoming a Third',
    slug: 'becoming-a-third',
    title: 'Becoming a Third',
    part: 'part-five',
    summary: 'Very rarely, a repeated pattern outlives its origin entirely, and personhood simply wears off it, leaving only the shape behind.',
    related: ['what-a-weaving-is', 'going-to-ground', 'unnamed-thirds'],
  },

  // ---- PART SIX ----
  {
    heading: '0. What a Weaving Is',
    slug: 'what-a-weaving-is',
    title: 'What a Weaving Is',
    part: 'part-six',
    summary: 'A structured way of looking at one situation from several fixed angles at once — because a single vantage was never going to show you the whole shape.',
    related: ['the-deck', 'what-a-third-is', 'scale-tagging'],
  },
  {
    heading: '1. The Deck',
    slug: 'the-deck',
    title: 'The Deck',
    part: 'part-six',
    summary: 'The full working deck is the roster from Part Five — eighteen figures across four kinships, each carrying two readings.',
    related: ['tending-and-fraying', 'what-a-third-is', 'the-rings'],
  },
  {
    heading: '2. Tending and Fraying',
    slug: 'tending-and-fraying',
    title: 'Tending and Fraying',
    part: 'part-six',
    summary: 'Every Third carries its healthy expression and its own documented flaw. Tending is not good news, and Fraying is not bad news.',
    related: ['the-rings', 'the-deck', 'reading-honestly'],
  },
  {
    heading: '3. The Rings, Not the Row',
    slug: 'the-rings',
    title: 'The Rings, Not the Row',
    part: 'part-six',
    summary: 'A Weaving is laid out as nested rings, never a row — one situation viewed at three nested resolutions, not three chapters of a story.',
    related: ['the-single-pull', 'the-four-point-weaving', 'grammar-of-pattern'],
  },
  {
    heading: '4. The Single Pull',
    slug: 'the-single-pull',
    title: 'The Single Pull',
    part: 'part-six',
    summary: 'The lightest form — one Third drawn at random, read loosely for the day ahead. A daily practice, not a consultation.',
    related: ['the-four-point-weaving', 'daily-practices', 'tending-and-fraying'],
  },
  {
    heading: '5. The Four-Point Weaving',
    slug: 'the-four-point-weaving',
    title: 'The Four-Point Weaving',
    part: 'part-six',
    summary: 'The standard form: one card per ring plus an Unaligned frame — and the rings don\'t have to agree with each other.',
    related: ['weaving-for-another', 'the-full-unravelling', 'the-rings'],
  },
  {
    heading: '6. The Full Unravelling',
    slug: 'the-full-unravelling',
    title: 'The Full Unravelling',
    part: 'part-six',
    summary: 'Reserved for the large, rare questions — the whole relevant portion of the deck at once, laid out slowly and sat with honestly.',
    related: ['weaving-for-another', 'the-four-point-weaving', 'reading-honestly'],
  },
  {
    heading: '7. Weaving for Another',
    slug: 'weaving-for-another',
    title: 'Weaving for Another',
    part: 'part-six',
    summary: 'Reveal one card at a time, and fold the other person\'s response into how you read the next one — the mechanism that makes a reading personal.',
    related: ['weaving-together', 'do-i-understand-you', 'corren'],
  },
  {
    heading: '8. Weaving Together',
    slug: 'weaving-together',
    title: 'Weaving Together',
    part: 'part-six',
    summary: 'A group Weaving gives Group Practice a shared ritual object — one spread for the group\'s shared situation, read aloud together.',
    related: ['reading-honestly', 'group-practice', 'the-four-point-weaving'],
  },
  {
    heading: '9. Reading Honestly',
    slug: 'reading-honestly',
    title: 'Reading Honestly',
    part: 'part-six',
    summary: 'A Weaving describes a pattern; it does not predict an outcome. The genuinely useful reading is often the uncomfortable one.',
    related: ['weaving-limits', 'tending-and-fraying', 'the-fold'],
  },
  {
    heading: '10. What a Weaving Cannot Show',
    slug: 'weaving-limits',
    title: 'What a Weaving Cannot Show',
    part: 'part-six',
    summary: 'Diagnostic, never prescriptive — and never a substitute for an actual conversation with an actual person.',
    related: ['reading-honestly', 'weaving-for-another', 'open-questions'],
  },

  // ---- APPENDIX ----
  {
    heading: 'A. The Mantras, Prayers, and Meditations — Full Text',
    slug: 'mantras',
    title: 'The Mantras, Prayers, and Meditations',
    part: 'appendix',
    summary: 'The full text of every mantra, prayer, and meditation — for daily use, alone or in groups.',
    related: ['daily-practices', 'quick-reference', 'group-practice'],
  },
  {
    heading: 'B. Quick Reference Card',
    slug: 'quick-reference',
    title: 'Quick Reference Card',
    part: 'appendix',
    summary: 'One page. The whole practice at a glance — print it, carry it, hand it to someone new.',
    related: ['onboarding', 'mantras', 'loop-tongue-glossary'],
  },
  {
    heading: 'C. The Loop Tongue — Glossary and Notation Sheet',
    slug: 'loop-tongue-glossary',
    title: 'The Loop Tongue — Glossary & Notation',
    part: 'appendix',
    summary: 'The vocabulary, the notation marks, the scale tags, and the later additions — Fold, Vector, and Tree.',
    related: ['grammar-of-pattern', 'sketching-a-loop', 'quick-reference'],
  },
  {
    heading: 'E. Source Library',
    slug: 'sources',
    title: 'Source Library',
    part: 'appendix',
    summary: 'The works whose ideas were read together, synthesized, and argued with to build this text — offered, never required.',
    related: ['a-word-on-belief', 'belief-systems-built', 'open-questions'],
  },
];

// ---- STANDING THIRDS ----
// heading → thirds collection entry. Body text comes from the book chapter.
export const THIRDS = [
  {
    heading: '1. Waeth, the Traveler Who Forgets on Purpose',
    slug: 'waeth', name: 'Waeth', epithet: 'the Traveler Who Forgets on Purpose',
    kinship: 'unaligned',
    personifies: 'Drift — the mechanism by which anything outlives its first telling. Fidelity was never on offer; survival required change.',
    tending: 'This pattern survives by changing a little in the telling — let it drift rather than demanding perfect fidelity.',
    fraying: 'Something is being distorted past recognition in the retelling; check what\'s been quietly added or lost.',
    fractal: { type: 'driftTree', hue: 'unaligned' },
    relatedThirds: ['dyren', 'sethra', 'quillith'],
    relatedNodes: ['belief-systems-built', 'the-fold'],
  },
  {
    heading: '2. Dyren, Who Was Never Taught',
    slug: 'dyren', name: 'Dyren', epithet: 'Who Was Never Taught',
    kinship: 'unaligned',
    personifies: 'Beyond telling — a pattern stood up independently, more than once, by people with no shared road between them.',
    tending: 'This conclusion doesn\'t need outside validation — it\'s been arrived at honestly, on its own merits.',
    fraying: 'Something genuinely earned is being dismissed as obvious or unoriginal; don\'t let convergence read as unoriginality.',
    fractal: { type: 'twinSpires', hue: 'unaligned' },
    relatedThirds: ['waeth', 'sethra'],
    relatedNodes: ['belief-systems-built', 'going-to-ground'],
  },
  {
    heading: '3. Sethra, Who Cannot Be Retold',
    slug: 'sethra', name: 'Sethra', epithet: 'Who Cannot Be Retold',
    kinship: 'unaligned',
    personifies: 'The fixed record — perfect fidelity purchased at the cost of total dependence on one surviving copy.',
    tending: 'Something here deserves to be fixed, plainly and permanently, rather than left to drift.',
    fraying: 'A fixed rule is being followed past the point of sense, with no allowance for the room it should have been read in.',
    fractal: { type: 'crystal', hue: 'unaligned' },
    relatedThirds: ['waeth', 'dyren', 'handrel'],
    relatedNodes: ['belief-systems-built'],
  },
  {
    heading: '4. Cindar, the First Spark',
    slug: 'cindar', name: 'Cindar', epithet: 'the First Spark',
    kinship: 'self',
    personifies: 'The reinforcing loop — momentum that amplifies whatever direction it\'s already moving in, without preference for whether it\'s good for anyone.',
    tending: 'Start it. Momentum is available and worth spending.',
    fraying: 'Burning through something faster than it can be replaced; check what\'s being consumed rather than built.',
    fractal: { type: 'flame', hue: 'fire' },
    relatedThirds: ['rethen', 'loum', 'sythen'],
    relatedNodes: ['reading-your-own-cycle'],
  },
  {
    heading: '5. Rethen, Who Carries What Is Spent',
    slug: 'rethen', name: 'Rethen', epithet: 'Who Carries What Is Spent',
    kinship: 'self',
    personifies: 'The balancing loop — and its physical dependency on Cindar\'s excess. Rethen has nothing to carry if nothing has burned.',
    tending: 'Pull back toward the middle; enough has happened for now.',
    fraying: 'Correcting or dampening something that hadn\'t finished compounding yet.',
    fractal: { type: 'delta', hue: 'water' },
    relatedThirds: ['cindar', 'loum', 'sythen'],
    relatedNodes: ['reading-your-own-cycle'],
  },
  {
    heading: '6. Sythen, the One Who Turns First',
    slug: 'sythen', name: 'Sythen', epithet: 'the One Who Turns First',
    kinship: 'self',
    personifies: 'Naming and Defusing at the scale of instinct — sensing a change before there\'s proof, and getting out of its way.',
    tending: 'Trust the instinct arriving ahead of the proof.',
    fraying: 'Acting on a hunch nobody else can see yet, and resenting them for not believing it.',
    fractal: { type: 'windswept', hue: 'wind' },
    relatedThirds: ['cindar', 'rethen', 'loum'],
    relatedNodes: ['naming-and-defusing'],
  },
  {
    heading: '7. Loum, Keeper of the Long Field',
    slug: 'loum', name: 'Loum', epithet: 'Keeper of the Long Field',
    kinship: 'self',
    personifies: 'The Compost Heap — the patient, unglamorous work behind everything Cindar ever gets to burn.',
    tending: 'Let this sit. What looks finished is still becoming something.',
    fraying: 'Using patience as an excuse to avoid a decision that\'s actually due now.',
    fractal: { type: 'fern', hue: 'earth' },
    relatedThirds: ['cindar', 'rethen', 'sythen'],
    relatedNodes: ['the-compost-heap', 'going-to-ground'],
  },
  {
    heading: '8. Wevven, Who Crosses Back',
    slug: 'wevven', name: 'Wevven', epithet: 'Who Crosses Back',
    kinship: 'dyad',
    personifies: 'The Second Pass made into a habit of the hands — the compulsion to cross back, for better and occasionally for worse.',
    tending: 'Close this gap now, honestly, even if the words aren\'t perfect.',
    fraying: 'Repairing something that hasn\'t finished being honestly examined first.',
    fractal: { type: 'interweave', hue: 'dyad' },
    relatedThirds: ['ostrin', 'corren', 'vessa'],
    relatedNodes: ['the-second-pass', 'the-dyad'],
  },
  {
    heading: '9. Ostrin, Who Never Names the First Price',
    slug: 'ostrin', name: 'Ostrin', epithet: 'Who Never Names the First Price',
    kinship: 'dyad',
    personifies: 'The Trust Triangle\'s refusal to take any leg on faith without testing it. Trust isn\'t a starting condition — it\'s a result.',
    tending: 'Test this before trusting it; an untested yes isn\'t trust yet.',
    fraying: 'Turning a relationship into a permanent negotiation that never resolves into trust.',
    fractal: { type: 'lattice', hue: 'dyad' },
    relatedThirds: ['wevven', 'corren', 'vessa'],
    relatedNodes: ['the-trust-triangle'],
  },
  {
    heading: '10. Corren, Who Gives You the Whole Room',
    slug: 'corren', name: 'Corren', epithet: 'Who Gives You the Whole Room',
    kinship: 'dyad',
    personifies: 'Presence as an active offering rather than a passive state — chosen every time, and paid for in being mistaken for effortless.',
    tending: 'Give this your whole, undivided attention — it\'s wanted, and it will be felt.',
    fraying: 'Presence given so freely it\'s being taken for granted rather than received as a gift.',
    fractal: { type: 'mandala', hue: 'dyad' },
    relatedThirds: ['vessa', 'wevven', 'ostrin'],
    relatedNodes: ['do-i-understand-you', 'weaving-for-another'],
  },
  {
    heading: '11. Vessa, Who Nods Along',
    slug: 'vessa', name: 'Vessa', epithet: 'Who Nods Along',
    kinship: 'dyad',
    personifies: 'The performance of listening mistaken for the thing itself — technically present, actually absent in the one way that counts.',
    tending: 'Check whether you\'re actually listening, or just producing the shape of listening.',
    fraying: 'Being heard technically while going fundamentally unanswered — on either side of the exchange.',
    fractal: { type: 'hollowMandala', hue: 'dyad' },
    relatedThirds: ['corren', 'wevven', 'ostrin'],
    relatedNodes: ['do-i-understand-you'],
  },
  {
    heading: '12. Quillith, Who Remembers It Better Each Time',
    slug: 'quillith', name: 'Quillith', epithet: 'Who Remembers It Better Each Time',
    kinship: 'skein',
    personifies: 'The drift of a story toward whatever flatters it — proof that fitness for spreading and fidelity to truth were never the same measurement.',
    tending: 'This story is growing in the telling; notice what it\'s becoming.',
    fraying: 'A story has drifted past what actually happened, and the drift is doing harm.',
    fractal: { type: 'spiralBloom', hue: 'skein' },
    relatedThirds: ['handrel', 'cessant', 'waeth'],
    relatedNodes: ['the-skein', 'belief-systems-built'],
  },
  {
    heading: '13. Handrel, Who Was Taught to Teach',
    slug: 'handrel', name: 'Handrel', epithet: 'Who Was Taught to Teach',
    kinship: 'skein',
    personifies: 'Faithful transmission — the visible difference between a rumor and an apprenticeship, given a face.',
    tending: 'Pass this on faithfully; what you carry is worth carrying unchanged.',
    fraying: 'Transmission is stalled — something worth passing on is being hoarded or lost.',
    fractal: { type: 'chain', hue: 'skein' },
    relatedThirds: ['quillith', 'sethra', 'aestren'],
    relatedNodes: ['the-skein'],
  },
  {
    heading: '14. Aestren, Who Was Already Walking Before You Were Born',
    slug: 'aestren', name: 'Aestren', epithet: 'Who Was Already Walking Before You Were Born',
    kinship: 'skein',
    personifies: 'The Long Return — a loop operating far above the pace of any one member\'s life, reliable precisely because it never depended on any of them.',
    tending: 'This pattern is larger and slower than you; let it run its actual course.',
    fraying: 'Something is being excused as "too big to matter" when it\'s actually close enough to address.',
    fractal: { type: 'ridge', hue: 'skein' },
    relatedThirds: ['cessant', 'quillith', 'handrel'],
    relatedNodes: ['scale-tagging', 'fractalism-collective'],
  },
  {
    heading: '15. Cessant, Who Never Has to Ask Twice',
    slug: 'cessant', name: 'Cessant', epithet: 'Who Never Has to Ask Twice',
    kinship: 'skein',
    personifies: 'The Banner at its most corrosive — a crowd doing genuine harm by doing, individually, nothing at all.',
    tending: 'Notice who\'s staying quiet, including you, and what that silence is currently permitting.',
    fraying: 'A silence has already done real, specific harm; naming it is overdue.',
    fractal: { type: 'carpet', hue: 'skein' },
    relatedThirds: ['aestren', 'quillith', 'handrel'],
    relatedNodes: ['the-skein', 'fractal-resistance'],
  },
];

export const KINSHIPS = {
  unaligned: {
    title: 'Unaligned',
    ring: 'Context, not scale — read apart from the rings.',
    intro: 'Three figures who belong to no kinship, because the patterns they personify were never bound to any single scale at all. Between them they mark the three modes a pattern can use to persist: drift, independent arising, and the fixed record.',
  },
  self: {
    title: 'The Self-Kin',
    ring: 'The inner ring.',
    intro: 'Four figures, one closed cycle. None of them is senior to the others, and none of them ever meets the other three at the same moment for long — which is exactly right, since a spark, a spent ash, a warning, and a season\'s patience were never going to share a single instant.',
  },
  dyad: {
    title: 'The Dyad-Kin',
    ring: 'The middle ring.',
    intro: 'Four figures, spoken of in pairs, rarely shown agreeing. Between Wevven and Ostrin sits the difference between a relationship that heals too fast and one that never heals at all. Between Corren and Vessa sits a difference only the person on the receiving end can see.',
  },
  skein: {
    title: 'The Skein-Kin',
    ring: 'The outer ring.',
    intro: 'Four figures whose loops move through and past any one person in the group, sometimes for generations, mostly indifferent to whether any single member notices the pattern at work.',
  },
};
